In [1]:
import json
import requests
import pandas as pd
import numpy as np

In [2]:
%run desktop/opentransit-metrics/mykelu/eclipses.py

In [3]:
def load_json(filename = 'routes24h20181015v2.json'):
    with open(filename, 'r') as f:
        return json.load(f)

In [4]:
test = load_json()

In [5]:
# get all stops from a given data set
def get_all_stops(data):
    bus_stops = pd.DataFrame(columns = ["VID", "DATE", "TIME", "SID", "DID", "ROUTE"])
    
    for route in [ele['rid'] for ele in test]:
        print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: Starting with {route}.")
        try:
            stop_ids = [stop['id']
                for stop
                in requests.get(f"http://restbus.info/api/agencies/sf-muni/routes/{route}").json()['stops']]
                 
            route_data = [ele for ele in test if ele['rid'] == route]

            for stop_id in stop_ids:
                try:
                    stops = produce_stops(route_data, route)
                except:
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: could not produce stops df for {stop_id} on route {route}. Skipping.")
                    break

                buses = produce_buses(route_data)

                stop = stops[stops['SID'] == stop_id].squeeze()

                try: 
                    buses = buses[buses['DID'] == stop['DID']]
                except ValueError: # accounts for stops with no associated direction
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: no direction associated to {stop_id} on route {route}. Skipping.")
                    continue

                eclipses = find_eclipses(buses, stop)
                nadirs = find_nadirs(eclipses)

                try:
                    nadirs["TIME"] = nadirs["TIME"].apply(lambda x: datetime.fromtimestamp(x//1000, timezone(timedelta(hours = -8))))
                    nadirs['DATE'] = nadirs['TIME'].apply(lambda x: x.date())
                    nadirs['TIME'] = nadirs['TIME'].apply(lambda x: x.time())
                    nadirs["SID"] = stop_id
                    nadirs["DID"] = stop["DID"]
                    nadirs["ROUTE"] = route
                    bus_stops = bus_stops.append(nadirs, sort = True)
                except:
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: could not produce stops df for {stop_id} on route {route}. Skipping.", end = "\r")              
        except KeyError:
            print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: KeyError at {route}!")
            continue
                      
    if len(bus_stops) > 0:
        bus_stops['timestamp'] = bus_stops[['DATE', 'TIME']].apply(lambda x: datetime.strptime(f"{x['DATE'].isoformat()} {x['TIME'].isoformat()} -0800", 
                                                                                       "%Y-%m-%d %H:%M:%S %z"), axis = 'columns')
    
    return bus_stops

In [6]:
df = get_all_stops(test)

Sun Feb 24 10:56:36 PM: Starting with 1.
Sun Feb 24 11:04:17 PM: Starting with 3.
Sun Feb 24 11:05:25 PM: no direction associated to 6088 on route 3. Skipping.
Sun Feb 24 11:06:54 PM: Starting with 5.
Sun Feb 24 11:09:18 PM: no direction associated to 3183 on route 5. Skipping.
Sun Feb 24 11:09:20 PM: no direction associated to 3923 on route 5. Skipping.
Sun Feb 24 11:09:21 PM: no direction associated to 3200 on route 5. Skipping.
Sun Feb 24 11:09:22 PM: no direction associated to 34735 on route 5. Skipping.
Sun Feb 24 11:10:49 PM: no direction associated to 4850 on route 5. Skipping.
Sun Feb 24 11:10:51 PM: no direction associated to 7884 on route 5. Skipping.
Sun Feb 24 11:10:52 PM: no direction associated to 37563 on route 5. Skipping.
Sun Feb 24 11:11:24 PM: no direction associated to 3161 on route 5. Skipping.
Sun Feb 24 11:11:25 PM: no direction associated to 7775 on route 5. Skipping.
Sun Feb 24 11:11:25 PM: Starting with 6.
Sun Feb 24 11:14:36 PM: no direction associated to 7408 on route 6. Skipping.
Sun Feb 24 11:18:05 PM: no direction associated to 3244 on route 6. Skipping.
Sun Feb 24 11:18:05 PM: Starting with 7.
Sun Feb 24 11:24:38 PM: Starting with 8.
Sun Feb 24 11:31:43 PM: Starting with 9.
Sun Feb 24 11:35:48 PM: Starting with 10.
Sun Feb 24 11:39:26 PM: no direction associated to 5850 on route 10. Skipping.
Sun Feb 24 11:43:33 PM: no direction associated to 35850 on route 10. Skipping.
Sun Feb 24 11:43:33 PM: Starting with 12.
Sun Feb 24 11:48:02 PM: Starting with 14.
Sun Feb 24 11:50:28 PM: no direction associated to 37742 on route 14. Skipping.
Sun Feb 24 11:50:47 PM: no direction associated to 7742 on route 14. Skipping.
Sun Feb 24 11:53:47 PM: Starting with 18.
Sun Feb 24 11:56:22 PM: Starting with 19.
Mon Feb 25 12:02:32 AM: Starting with 21.
Mon Feb 25 12:05:13 AM: no direction associated to 4236 on route 21. Skipping.
Mon Feb 25 12:05:13 AM: Starting with 22.
Mon Feb 25 12:09:30 AM: could not produce stops df for 33410 on route 22. Skipping.
Mon Feb 25 12:09:30 AM: Starting with 23.
Mon Feb 25 12:09:37 AM: could not produce stops df for 5879 on route 23. Skipping.
Mon Feb 25 12:09:37 AM: Starting with 24.
Mon Feb 25 12:09:50 AM: could not produce stops df for 4415 on route 24. Skipping.
Mon Feb 25 12:09:50 AM: Starting with 25.
Mon Feb 25 12:10:31 AM: Starting with 27.
Mon Feb 25 12:13:28 AM: could not produce stops df for 3752 on route 27. Skipping.
Mon Feb 25 12:13:28 AM: Starting with 28.
Mon Feb 25 12:16:42 AM: Starting with 29.
Mon Feb 25 12:25:46 AM: Starting with 2.
Mon Feb 25 12:25:47 AM: no direction associated to 6497 on route 2. Skipping.
Mon Feb 25 12:26:50 AM: no direction associated to 6088 on route 2. Skipping.
Mon Feb 25 12:27:23 AM: no direction associated to 6089 on route 2. Skipping.
Mon Feb 25 12:28:26 AM: no direction associated to 5658 on route 2. Skipping.
Mon Feb 25 12:28:27 AM: no direction associated to 6475 on route 2. Skipping.
Mon Feb 25 12:28:28 AM: no direction associated to 36497 on route 2. Skipping.
Mon Feb 25 12:29:07 AM: Starting with 30.
Mon Feb 25 12:33:41 AM: no direction associated to 3161 on route 30. Skipping.
Mon Feb 25 12:33:41 AM: Starting with 31.
Mon Feb 25 12:41:01 AM: Starting with 33.
Mon Feb 25 12:45:55 AM: Starting with 37.
Mon Feb 25 12:51:21 AM: Starting with 38.
Mon Feb 25 12:54:03 AM: no direction associated to 35511 on route 38. Skipping.
Mon Feb 25 12:57:17 AM: Starting with 43.
Mon Feb 25 01:07:06 AM: Starting with 44.
Mon Feb 25 01:15:30 AM: no direction associated to 4387 on route 44. Skipping.
Mon Feb 25 01:15:30 AM: Starting with 45.
Mon Feb 25 01:18:36 AM: Starting with 47.
Mon Feb 25 01:21:35 AM: Starting with 48.
Mon Feb 25 01:23:02 AM: no direction associated to 33462 on route 48. Skipping.
Mon Feb 25 01:24:53 AM: no direction associated to 36744 on route 48. Skipping.
Mon Feb 25 01:28:17 AM: Starting with 49.
Mon Feb 25 01:31:55 AM: Starting with 54.
Mon Feb 25 01:38:15 AM: Starting with 55.
Mon Feb 25 01:39:08 AM: Starting with 41.
Mon Feb 25 01:40:17 AM: no direction associated to 6778 on route 41. Skipping.
Mon Feb 25 01:41:22 AM: Starting with 57.
Mon Feb 25 01:44:24 AM: Starting with 66.
Mon Feb 25 01:47:11 AM: Starting with 36.
Mon Feb 25 01:53:34 AM: Starting with 52.
Mon Feb 25 01:56:23 AM: Starting with 35.
Mon Feb 25 01:58:49 AM: Starting with 56.
Mon Feb 25 01:59:50 AM: no direction associated to 34575 on route 56. Skipping.
Mon Feb 25 02:00:59 AM: Starting with 39.
Mon Feb 25 02:02:28 AM: Starting with 90.
Mon Feb 25 02:04:11 AM: Starting with 91.
Mon Feb 25 02:10:46 AM: Starting with J.
Mon Feb 25 02:12:16 AM: no direction associated to 4510 on route J. Skipping.
Mon Feb 25 02:13:51 AM: no direction associated to 7903 on route J. Skipping.
Mon Feb 25 02:13:54 AM: no direction associated to 4447 on route J. Skipping.
Mon Feb 25 02:13:55 AM: no direction associated to 4448 on route J. Skipping.
Mon Feb 25 02:13:57 AM: no direction associated to 37217 on route J. Skipping.
Mon Feb 25 02:13:57 AM: Starting with N.
Mon Feb 25 02:18:59 AM: no direction associated to 7405 on route N. Skipping.
Mon Feb 25 02:19:01 AM: no direction associated to 5241 on route N. Skipping.
Mon Feb 25 02:19:04 AM: no direction associated to 7903 on route N. Skipping.
Mon Feb 25 02:19:06 AM: no direction associated to 7397 on route N. Skipping.
Mon Feb 25 02:19:08 AM: no direction associated to 35241 on route N. Skipping.
Mon Feb 25 02:19:10 AM: no direction associated to 37217 on route N. Skipping.
Mon Feb 25 02:19:10 AM: Starting with PH.
Mon Feb 25 02:22:21 AM: Starting with 67.
Mon Feb 25 02:24:13 AM: Starting with 30X.
Mon Feb 25 02:25:44 AM: Starting with 14R.
Mon Feb 25 02:28:36 AM: Starting with 38R.
Mon Feb 25 02:33:11 AM: Starting with 82X.
Mon Feb 25 02:33:43 AM: Starting with 7X.
Mon Feb 25 02:36:02 AM: Starting with 88.
Mon Feb 25 02:36:29 AM: Starting with 83X.
Mon Feb 25 02:36:30 AM: KeyError at 83X!
Mon Feb 25 02:36:30 AM: Starting with 14X.
Mon Feb 25 02:38:28 AM: Starting with 81X.
Mon Feb 25 02:38:37 AM: Starting with E.
Mon Feb 25 02:38:37 AM: KeyError at E!
Mon Feb 25 02:38:38 AM: Starting with F.
Mon Feb 25 02:42:21 AM: Starting with M.
Mon Feb 25 02:43:34 AM: no direction associated to 7058 on route M. Skipping.
Mon Feb 25 02:45:43 AM: no direction associated to 37058 on route M. Skipping.
Mon Feb 25 02:45:47 AM: no direction associated to 6744 on route M. Skipping.
Mon Feb 25 02:45:49 AM: no direction associated to 7903 on route M. Skipping.
Mon Feb 25 02:45:50 AM: no direction associated to 36738 on route M. Skipping.
Mon Feb 25 02:45:52 AM: no direction associated to 37217 on route M. Skipping.
Mon Feb 25 02:45:52 AM: Starting with L.
Mon Feb 25 02:47:43 AM: no direction associated to 4510 on route L. Skipping.
Mon Feb 25 02:47:45 AM: no direction associated to 7058 on route L. Skipping.
Mon Feb 25 02:47:46 AM: no direction associated to 17058 on route L. Skipping.
Mon Feb 25 02:48:24 AM: no direction associated to 4509 on route L. Skipping.
Mon Feb 25 02:49:59 AM: no direction associated to 37058 on route L. Skipping.
Mon Feb 25 02:50:01 AM: no direction associated to 7903 on route L. Skipping.
Mon Feb 25 02:50:02 AM: no direction associated to 6738 on route L. Skipping.
Mon Feb 25 02:50:05 AM: no direction associated to 37217 on route L. Skipping.
Mon Feb 25 02:50:06 AM: no direction associated to 6744 on route L. Skipping.
Mon Feb 25 02:50:06 AM: Starting with PM.
Mon Feb 25 02:52:06 AM: Starting with NX.
Mon Feb 25 02:52:37 AM: Starting with 38BX.
Mon Feb 25 02:53:32 AM: Starting with 1AX.
Mon Feb 25 02:54:24 AM: Starting with 1BX.
Mon Feb 25 02:55:07 AM: Starting with 9R.
Mon Feb 25 02:56:47 AM: no direction associated to 36575 on route 9R. Skipping.
Mon Feb 25 02:58:41 AM: Starting with C.
Mon Feb 25 03:00:15 AM: Starting with 38AX.
Mon Feb 25 03:00:49 AM: Starting with 31BX.
Mon Feb 25 03:01:39 AM: Starting with 31AX.
Mon Feb 25 03:02:50 AM: Starting with 8AX.
Mon Feb 25 03:04:29 AM: Starting with 8BX.
Mon Feb 25 03:07:20 AM: Starting with 5R.
Mon Feb 25 03:10:37 AM: no direction associated to 7775 on route 5R. Skipping.
Mon Feb 25 03:10:44 AM: no direction associated to 3161 on route 5R. Skipping.
Mon Feb 25 03:10:44 AM: Starting with 28R.

In [7]:
df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318777 entries, 1 to 28135
Data columns (total 7 columns):
DATE         318777 non-null object
DID          318777 non-null object
ROUTE        318777 non-null object
SID          318777 non-null object
TIME         318777 non-null object
VID          318777 non-null object
timestamp    318777 non-null datetime64[ns, UTC-08:00]
dtypes: datetime64[ns, UTC-08:00](1), object(6)
memory usage: 107.3 MB

In [9]:
# duplicate indices are coming from a combination of combining multiple dataframes and duplicate stops (simultaneous stops at different stop ids)
df[df.index == 970]

,DATE,DID,ROUTE,SID,TIME,VID,timestamp
970,2018-10-14,9____O_N00,9,6569,23:58:15,8800,2018-10-14 23:58:15-08:00
970,2018-10-14,9____O_N00,9,6583,23:58:15,8800,2018-10-14 23:58:15-08:00
970,2018-10-14,14___I_F00,14,5693,23:31:45,7211,2018-10-14 23:31:45-08:00
970,2018-10-15,19___I_F00,19,6999,00:05:30,8422,2018-10-15 00:05:30-08:00
970,2018-10-15,44___O_F00,44,3694,00:08:00,8840,2018-10-15 00:08:00-08:00
970,2018-10-15,55___I_F00,55,3291,05:57:53,8869,2018-10-15 05:57:53-08:00
970,2018-10-15,55___I_F00,55,33293,05:57:53,8869,2018-10-15 05:57:53-08:00
970,2018-10-15,66___I_F00,66,4861,06:12:53,8519,2018-10-15 06:12:53-08:00
970,2018-10-15,66___I_F00,66,4859,06:12:53,8519,2018-10-15 06:12:53-08:00
970,2018-10-15,91___I_N00,91,5792,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,3377,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,3354,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,7448,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,PH___O_F00,PH,5156,05:42:22,24,2018-10-15 05:42:22-08:00
970,2018-10-15,PH___O_F00,PH,5164,05:42:22,24,2018-10-15 05:42:22-08:00

In [10]:
with open('routes20181015v2stops.json', 'w') as f:
    df.reindex(index = range(len(df)).to_json(f)